// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entities "github.com/koki-develop/lgtm-generator/backend/src/entities"

	mock "github.com/stretchr/testify/mock"
)

// ReportsRepository is an autogenerated mock type for the ReportsRepository type
type ReportsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: rpt
func (_m *ReportsRepository) Create(rpt *entities.Report) error {
	ret := _m.Called(rpt)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Report) error); ok {
		r0 = rf(rpt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
