version: '3'

services:
  app:
    image: lgtm-generator-backend-app
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
      target: build
    command: go run github.com/cosmtrek/air
    ports:
      - 8080:8080
    volumes:
      - .:/var/task
      - go_mod:/go/pkg/mod
    environment:
      STAGE: local
      GOOGLE_API_KEY: $GOOGLE_API_KEY
      GOOGLE_CUSTOM_SEARCH_ENGINE_ID: $GOOGLE_CUSTOM_SEARCH_ENGINE_ID
      NOTIFICATION_SLACK_ACCESS_TOKEN: $NOTIFICATION_SLACK_ACCESS_TOKEN

  bucket:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - bucket_data:/export
    environment:
      MINIO_ROOT_USER: DUMMY_AWS_ACCESS_KEY_ID
      MINIO_ROOT_PASSWORD: DUMMY_AWS_SECRET_ACCESS_KEY
    entrypoint: sh
    command: |
      -c "
      mkdir -p /export/lgtm-generator-backend-local-images
      /usr/bin/docker-entrypoint.sh server /export --console-address ':9001'
      "

  dynamodb:
    image: lgtm-generator-backend-dynamodb
    command: yarn run serverless dynamodb start --stage local
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: ./containers/dynamodb/Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - dynamodb_data:/app/data

volumes:
  bucket_data:
  dynamodb_data:
  go_mod:
  node_modules:
