version: '3'

services:
  api:
    command: go run github.com/cosmtrek/air
    image: lambci/lambda:build-go1.x
    working_dir: /app
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - go_mod:/go/pkg/mod
    environment:
      STAGE: local
    env_file: .env
    depends_on:
      - dynamodb

  bucket:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: DUMMY_AWS_ACCESS_KEY_ID
      MINIO_ROOT_PASSWORD: DUMMY_AWS_SECRET_ACCESS_KEY
    entrypoint: sh
    command: |
      -c "
      mkdir -p /export/lgtm-generator-backend-local-lgtms
      /usr/bin/minio server /export --console-address ':9001'
      "

  dynamodb:
    image: lgtm-generator-backend-dynamodb
    command: yarn run sls dynamodb start --stage local
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: ./containers/dynamodb/Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  go_mod:
  dynamodb_data:
  node_modules:
