version: '3'

services:
  bucket:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - bucket_data:/export
    environment:
      MINIO_ROOT_USER: DUMMY_AWS_ACCESS_KEY_ID
      MINIO_ROOT_PASSWORD: DUMMY_AWS_SECRET_ACCESS_KEY
    entrypoint: sh
    command: |
      -c "
      mkdir -p /export/lgtm-generator-backend-local-images
      /usr/bin/docker-entrypoint.sh server /export --console-address ':9001'
      "

  dynamodb:
    image: amazon/dynamodb-local:1.18.0
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    ports:
      - 8000:8000
    volumes:
      - dynamodb_data:/data

volumes:
  bucket_data:
  dynamodb_data:
