service: lgtm-generator-backend

frameworkVersion: "2"

provider:
  name: aws
  profile: default
  region: us-east-1
  stage: ${opt:stage, "dev"}
  lambdaHashingVersion: 20201221
  ecr:
    images:
      apiimage:
        path: ./

package:
  patterns:
    - "!./**"
    - ./bin/**

functions:
  api:
    image:
      name: apiimage
      entryPoint:
        - "/app/build/api"
    events:
      - http:
          method: get
          path: /v1/h
