service: lgtm-generator-backend

frameworkVersion: "2"

custom:
  product: ${self:service}
  prefix: ${self:custom.product}-${self:provider.stage}

provider:
  name: aws
  profile: default
  region: us-east-1
  stage: ${opt:stage, "dev"}
  lambdaHashingVersion: 20201221
  ecr:
    images:
      apiimage:
        path: ./
  apiName: ${self:custom.prefix}
  environment:
    GOOGLE_API_KEY: ${file(./secrets.yml):googleApiKey}
    GOOGLE_CUSTOM_SEARCH_ENGINE_ID: ${file(./secrets.yml):googleCustomSearchEngineId}

package:
  patterns:
    - "!./**"
    - ./bin/**

functions:
  api:
    image:
      name: apiimage
      entryPoint:
        - "/app/build/api"
    events:
      - http:
          method: get
          path: /v1/h
      - http:
          method: get
          path: /v1/images
          request:
            parameters:
              querystrings:
                q: true
      - http:
          method: get
          path: /v1/lgtms
      - http:
          method: post
          path: /v1/lgtms
