service: lgtm-generator-backend

frameworkVersion: "3"
useDotenv: true
configValidationMode: error

custom:
  product: ${self:service}
  prefix: ${self:custom.product}-${self:provider.stage}
  allowOrigin:
    local: http://localhost:3000
    dev: https://lgtm-generator-*-koki-develop.vercel.app
    prod: https://www.lgtmgen.org
  imageBaseUrl:
    local: http://localhost:9000/lgtm-generator-backend-local-images
    dev: https://dev.images.lgtmgen.org
    prod: https://images.lgtmgen.org
  datadog:
    site: ${env:DD_SITE}
    apiKey: ${env:DD_API_KEY}

provider:
  name: aws
  region: us-east-1
  stage: ${opt:stage, "dev"}
  logs:
    restApi: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::Join:
                - ":"
                - - arn:aws:dynamodb
                  - Ref: AWS::Region
                  - Ref: AWS::AccountId
                  - table/${self:custom.prefix}-*
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:DeleteObject
            - s3:ListBucket
          Resource:
            - Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - ${self:custom.prefix}-images
            - Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - ${self:custom.prefix}-images
                  - /*
  ecr:
    images:
      appimage:
        path: ./
        file: ./containers/app/Dockerfile
  apiName: ${self:custom.prefix}
  environment:
    STAGE: ${self:provider.stage}
    ALLOW_ORIGIN: ${self:custom.allowOrigin.${self:provider.stage}}
    IMAGES_BASE_URL: ${self:custom.imageBaseUrl.${self:provider.stage}}
    SLACK_API_TOKEN: ${env:SLACK_API_TOKEN}
    GOOGLE_API_KEY: ${env:GOOGLE_API_KEY}
    GOOGLE_CUSTOM_SEARCH_ENGINE_ID: ${env:GOOGLE_CUSTOM_SEARCH_ENGINE_ID}

package:
  individually: true

functions:
  api:
    image:
      name: appimage
      entryPoint:
        - "/var/task/build/api"
    timeout: 30
    events:
      # health check
      - http:
          method: get
          path: /h
      - http:
          method: get
          path: /v1/h

      # images
      - http:
          method: options
          path: /v1/images
      - http:
          method: get
          path: /v1/images
          request:
            parameters:
              querystrings:
                q: true

      # lgtms
      - http:
          method: options
          path: /v1/lgtms
      - http:
          method: get
          path: /v1/lgtms
          request:
            parameters:
              querystrings:
                after: false
      - http:
          method: post
          path: /v1/lgtms
      # reports
      - http:
          method: options
          path: /v1/reports
      - http:
          method: post
          path: /v1/reports
  deletelgtm:
    image:
      name: appimage
      entryPoint:
        - "/var/task/build/deletelgtm"
    timeout: 60

resources:
  Resources:
    LgtmsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.prefix}-lgtms
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
          - AttributeName: status
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: created_at
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: index_by_status
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
    ReportsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.prefix}-reports
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: created_at
            KeyType: RANGE
    GatewayResponseMissingAuthenticationToken:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseType: MISSING_AUTHENTICATION_TOKEN
        RestApiId:
          Ref: ApiGatewayRestApi
        StatusCode: "404"
        ResponseTemplates:
          application/json: '{"code":"NOT_FOUND"}'

plugins:
  - serverless-plugin-datadog
