service: lgtm-generator-backend

frameworkVersion: "2"

custom:
  product: ${self:service}
  prefix: ${self:custom.product}-${self:provider.stage}

provider:
  name: aws
  profile: default
  region: us-east-1
  stage: ${opt:stage, "dev"}
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
          Resource:
            - Fn::Join:
                - ":"
                - - arn:aws:dynamodb
                  - Ref: AWS::Region
                  - Ref: AWS::AccountId
                  - table/${self:custom.prefix}-*
  ecr:
    images:
      apiimage:
        path: ./
  apiName: ${self:custom.prefix}
  environment:
    STAGE: ${self:provider.stage}
    GOOGLE_API_KEY: ${file(./secrets.yml):googleApiKey}
    GOOGLE_CUSTOM_SEARCH_ENGINE_ID: ${file(./secrets.yml):googleCustomSearchEngineId}

package:
  patterns:
    - "!./**"
    - ./bin/**

functions:
  api:
    image:
      name: apiimage
      entryPoint:
        - "/app/build/api"
    events:
      - http:
          method: get
          path: /v1/h
      - http:
          method: get
          path: /v1/images
          request:
            parameters:
              querystrings:
                q: true
      - http:
          method: get
          path: /v1/lgtms
      - http:
          method: post
          path: /v1/lgtms

resources:
  Resources:
    LgtmsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.prefix}-lgtms
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
          - AttributeName: status
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: created_at
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: index_by_status
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
