service: lgtm-generator-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  api:
    handler: build/api
    events:
      - http:
          method: get
          path: /v1/h
