version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  docker: circleci/docker@1.6.0
  jq: circleci/jq@2.2.0
  slack: circleci/slack@4.4.2
  node: circleci/node@4.6.0

commands:
  go_mod_download:
    steps:
      - restore_cache:
          keys:
            - go-mod-v1-{{ .Branch }}-{{ checksum "go.sum" }}
      - run:
          name: go mod download
          command: go mod download -x
      - save_cache:
          paths:
            - /go/pkg/mod
          key: go-mod-v1-{{ .Branch }}-{{ checksum "go.sum" }}
  yarn_install:
    steps:
      - restore_cache:
          key: node-v2-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install --check-files
      - save_cache:
          key: node-v2-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  notify_status:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

jobs:
  backend_build:
    working_directory: ~/project/backend
    docker:
      - image: lambci/lambda:build-go1.x
    steps:
      - checkout:
          path: ~/project
      - jq/install
      - go_mod_download
      - run:
          name: test
          command: go test ./src/...
      - notify_status

  backend_deploy:
    working_directory: ~/project/backend
    machine: true
    parameters:
      stage:
        type: string
    steps:
      - checkout:
          path: ~/project
      # - jq/install
      - aws-cli/setup
      # - docker/install-docker
      - node/install:
          node-version: 14.17.4
          install-yarn: true
          yarn-version: 1.22.11
      - yarn_install
      - run:
          name: create secrets.yml
          command: |
            echo "googleApiKey: ${GOOGLE_API_KEY}"                               >> secrets.yml
            echo "googleCustomSearchEngineId: ${GOOGLE_CUSTOM_SEARCH_ENGINE_ID}" >> secrets.yml
            echo "slackAccessToken: ${APP_SLACK_ACCESS_TOKEN}"                   >> secrets.yml
      - run:
          name: deploy
          command: yarn run deploy --stage << parameters.stage >>
      - notify_status

workflows:
  build:
    jobs:
      # build
      - backend_build

      # approval
      - approval_deploy_dev:
          type: approval
          requires:
            - backend_build
      - slack/on-hold:
          requires:
            - backend_build

      # deploy
      - backend_deploy:
          stage: dev
          # FIXME: コメント解除
          # requires: [approval_deploy_dev]
