version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  docker: circleci/docker@1.6.0
  jq: circleci/jq@2.2.0

executors:
  go:
    docker:
      - image: golang:1.16
  node:
    docker:
      - image: node:14

commands:
  go_mod_download:
    steps:
      - restore_cache:
          keys:
            - go-mod-v1-{{ .Branch }}-{{ checksum "go.sum" }}
      - run:
          name: go mod download
          command: go mod download -x
      - save_cache:
          paths:
            - /go/pkg/mod
          key: go-mod-v1-{{ .Branch }}-{{ checksum "go.sum" }}
  yarn_install:
    steps:
      - restore_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install --check-files
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

jobs:
  backend_build:
    working_directory: ~/project/backend
    executor: go
    steps:
      - checkout:
          path: ~/project
      - go_mod_download
      - run:
          name: test
          command: go test ./src/...

  backend_deploy:
    working_directory: ~/project/backend
    executor: node
    parameters:
      stage:
        type: string
    steps:
      - checkout:
          path: ~/project
      - jq/install
      - aws-cli/setup
      - docker/install-docker
      - setup_remote_docker
      - yarn_install
      - run:
          name: deploy
          command: yarn run deploy --stage << parameters.stage >>

workflows:
  build:
    jobs:
      - backend_build
      - backend_deploy:
          stage: dev
          requires:
            - backend_build
