// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	iface "github.com/koki-develop/lgtm-generator/backend/src/infrastructures/iface"
	mock "github.com/stretchr/testify/mock"
)

// DynamoDBDelete is an autogenerated mock type for the DynamoDBDelete type
type DynamoDBDelete struct {
	mock.Mock
}

// Range provides a mock function with given fields: name, value
func (_m *DynamoDBDelete) Range(name string, value interface{}) iface.DynamoDBDelete {
	ret := _m.Called(name, value)

	var r0 iface.DynamoDBDelete
	if rf, ok := ret.Get(0).(func(string, interface{}) iface.DynamoDBDelete); ok {
		r0 = rf(name, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iface.DynamoDBDelete)
		}
	}

	return r0
}

// Run provides a mock function with given fields:
func (_m *DynamoDBDelete) Run() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
