// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	iface "github.com/koki-develop/lgtm-generator/backend/src/infrastructures/iface"
	mock "github.com/stretchr/testify/mock"
)

// DynamoDB is an autogenerated mock type for the DynamoDB type
type DynamoDB struct {
	mock.Mock
}

// Table provides a mock function with given fields: name
func (_m *DynamoDB) Table(name string) iface.DynamoDBTable {
	ret := _m.Called(name)

	var r0 iface.DynamoDBTable
	if rf, ok := ret.Get(0).(func(string) iface.DynamoDBTable); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iface.DynamoDBTable)
		}
	}

	return r0
}
