// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entities "github.com/koki-develop/lgtm-generator/backend/src/entities"

	mock "github.com/stretchr/testify/mock"
)

// ImageSearchEngine is an autogenerated mock type for the ImageSearchEngine type
type ImageSearchEngine struct {
	mock.Mock
}

// Search provides a mock function with given fields: q
func (_m *ImageSearchEngine) Search(q string) (entities.Images, error) {
	ret := _m.Called(q)

	var r0 entities.Images
	if rf, ok := ret.Get(0).(func(string) entities.Images); ok {
		r0 = rf(q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.Images)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
