// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LGTMGenerator is an autogenerated mock type for the LGTMGenerator type
type LGTMGenerator struct {
	mock.Mock
}

// Generate provides a mock function with given fields: src
func (_m *LGTMGenerator) Generate(src []byte) ([]byte, error) {
	ret := _m.Called(src)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(src)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(src)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
