// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	slack "github.com/slack-go/slack"
	mock "github.com/stretchr/testify/mock"
)

// SlackAPI is an autogenerated mock type for the SlackAPI type
type SlackAPI struct {
	mock.Mock
}

// PostMessage provides a mock function with given fields: msg
func (_m *SlackAPI) PostMessage(msg *slack.Msg) error {
	ret := _m.Called(msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(*slack.Msg) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
