import { Translate } from './translate';
import { ja } from './ja';

export const en: Translate = {
  APP_NAME: ja.APP_NAME,
  PRECAUTIONS: 'Precautions',
  PRECAUTIONS_ITEMS: [
    'Users are responsible for any and all liability related to images generated using this service. In the event that a third party suffers damage in relation to an image generated by the user, the operator will not be held liable on behalf of the user.',
    'The images generated by using this service will be published on the Internet.',
    'Please pay attention to the copyright of the original image. Do not generate images that are offensive to public order and morals or that are illegal. These images and any other images that the operator deems inappropriate may be deleted without notice.',
    'Please do not overload this service by sending an excessive number of requests.',
    'In addition, we reserve the right to prohibit access to certain users without notice when malicious use of the site is confirmed.',
  ],
  PRIVACY_POLICY: 'Privacy Policy',

  COPIED_TO_CLIPBOARD: 'Copied to clipboard',

  CONFIRM_GENERATION: 'Would you like to generate LGTM image with this image?',

  GENERATE: 'Generate',
  CANCEL: 'Cancel',

  ILLEGAL:
    'Illegal ( Copyright infringement, invasion of privacy, defamation, etc. )',
  INAPPROPRIATE: 'Inappropriate content',
  OTHER: 'Other',

  SUPPLEMENT: '( Optional ) Supplement',

  SEND: 'Send',

  NO_FAVORITES: 'There are no favorites yet.',

  SEE_MORE: 'See more',

  KEYWORD: 'Keyword',

  LGTM: 'LGTM',
  IMAGE_SEARCH: 'Image Search',
  FAVORITES: 'Favorites',

  UPLOAD: 'Upload',

  NOT_FOUND: 'Page not found',
};
