// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entities "github.com/koki-develop/lgtm-generator/backend/src/entities"

	mock "github.com/stretchr/testify/mock"
)

// ImagesUsecase is an autogenerated mock type for the ImagesUsecase type
type ImagesUsecase struct {
	mock.Mock
}

// Search provides a mock function with given fields: ipt
func (_m *ImagesUsecase) Search(ipt *entities.ImagesSearchInput) (entities.Images, error) {
	ret := _m.Called(ipt)

	var r0 entities.Images
	if rf, ok := ret.Get(0).(func(*entities.ImagesSearchInput) entities.Images); ok {
		r0 = rf(ipt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.Images)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entities.ImagesSearchInput) error); ok {
		r1 = rf(ipt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
