// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entities "github.com/koki-develop/lgtm-generator/backend/src/entities"

	mock "github.com/stretchr/testify/mock"
)

// ReportsUsecase is an autogenerated mock type for the ReportsUsecase type
type ReportsUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ipt
func (_m *ReportsUsecase) Create(ipt *entities.ReportCreateInput) (*entities.Report, error) {
	ret := _m.Called(ipt)

	var r0 *entities.Report
	if rf, ok := ret.Get(0).(func(*entities.ReportCreateInput) *entities.Report); ok {
		r0 = rf(ipt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Report)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entities.ReportCreateInput) error); ok {
		r1 = rf(ipt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
