name: Build

on:
  push:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum
          cache: true
      - run: go test ./...
