name: Release (dev)

on:
  push:
    branches:
      - develop
      - migrate-circleci-to-gh-actions # TODO: remove

jobs:
  # build:
  #   uses: ./.github/workflows/_build.yml
  #   secrets: inherit

  # release:
  #   needs: [build]
  #   uses: ./.github/workflows/_release.yml
  #   with:
  #     stage: dev
  #   secrets: inherit

  e2e:
    # needs: [release]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e2e
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5.0.5
        with:
          config-file: cypress.dev.config.ts
          record: true
          working-directory: e2e
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
