name: Release (dev)

on:
  push:
    branches:
      - develop

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    secrets: inherit

  release:
    needs: [build]
    uses: ./.github/workflows/_release.yml
    with:
      stage: dev
    secrets: inherit

  e2e:
    needs: [release]
    uses: ./.github/workflows/_e2e.yml
    secrets: inherit
